// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the free extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace AspireManifestGen;

using System;

/// <summary>
/// Helper class that exposes all GUIDs used across VS Package.
/// </summary>
internal sealed partial class PackageGuids
{
    public const string AspireManifestGenString = "caf1ee1b-7891-494a-8b1d-39bbff587cab";
    public static Guid AspireManifestGen = new Guid(AspireManifestGenString);
}
/// <summary>
/// Helper class that encapsulates all CommandIDs uses across VS Package.
/// </summary>
internal sealed partial class PackageIds
{
    public const int MyMenuGroup = 0x0001;
    public const int MyCommand = 0x0100;
}