// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace AspireManifestGen
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string AspireManifestGenString = "caf1ee1b-7891-494a-8b1d-39bbff587cab";
        public static Guid AspireManifestGen = new Guid(AspireManifestGenString);

        public const string UIContextGuidString = "f686d1d0-9ddf-47db-a0dc-59032e168f69";
        public static Guid UIContextGuid = new Guid(UIContextGuidString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int ContextMenuGroup = 0x0001;
        public const int MyCommand = 0x0100;
    }
}